services:
  db:
    image: postgres:15-alpine
    container_name: opbk_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: layducky/openbk-be:1.1.1
    container_name: opbk_backend
    restart: always
    env_file: .env.be
    expose:
      - "5000"
    depends_on:
      - db

  frontend:
    image: layducky/openbk-fe:1.1.4
    build:
      context: ../Open_BK_FE
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: ${NEXT_PUBLIC_GOOGLE_CLIENT_SECRET}
    container_name: opbk_frontend
    restart: always
    env_file: .env.fe
    expose:
      - "3000"
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    container_name: opbk_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
